### PR TITLE
Add profile

### PR DESCRIPTION
**Pull request by tresoldi**
This PR adds an actual profile (earlier code was just splitting the characters in forms). I kept all tonal annotations I could, using the slash notation, and tried to solve doubts by manually inspecting cognates.

The code is also re-organized a bit, including tests (so that it should be quick to pass buildbot later, but let's do it in a different step).

### CODE REVIEW

**Review by LinguList — COMMENTED** [review]
@tresoldi, your profile deletes not within brackets, due to your formspec, but you should in fact do that, as by now, you have forms like line 6, "lína [pl. mína]", which is obviously a case where what is in teh bracket should be deleted, as this is a plural form.

Either, you manually add your 10 cases with the bracket to the lexemes, or you should rather delete them, it would not make sense otherwise. I'd consider the same thing for all normal brackets `()` as well.

Otherwise, it looks okay. What a huge mess in terms of orthography here...

**Comment by tresoldi** [comment]
I'll fix it.

**Comment by SimonGreenhill** [comment]
Well done! I'm amazed that you managed this :)

**Comment by tresoldi** [comment]
Thanks, @SimonGreenhill , but as usual some specialist feedback would be needed (which, once more, is why we need to name the column "Segments" and not "Transcription" -- it is how I was able to convince some more phonologically inclined people of its value). I'm fixing the issue @LinguList raised and push again.

**Review by SimonGreenhill — APPROVED** [review]

**Comment by tresoldi** [comment]
@LinguList please check, I manually verified all instances with round and square parentheses (checking `cldf/forms.csv` should be enough). I'll merge once you approve.

**Comment by LinguList** [comment]
Thanks, it is fine by me.

**Pull request merged**
